import Footer from "@components/Footer";
import Navbar from "@components/Navbar";
import "@styles/globals.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient"></div>
        </div>
        <main>
          <Navbar/>
          {children}
          <Footer/>
        </main>
     
      </body>
    </html>
  )
}
